name: Validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate Kubernetes manifests
        uses: docker://ghcr.io/yannh/kubeconform:v0.6.7
        with:
          args: -summary -strict -ignore-missing-schemas apps argocd
